chore: fix EOF newline issue after pre-commit hook

diff --git a/.github/workflows/check-sdist.yml b/.github/workflows/check-sdist.yml
--- a/.github/workflows/check-sdist.yml
+++ b/.github/workflows/check-sdist.yml
@@ -4,7 +4,7 @@ permissions:
 
 on:
   schedule:
-    - cron: '0 0 * * *'
+    - cron: "0 0 * * *"
 
 jobs:
   check-sdist:
@@ -16,12 +16,28 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         with:
-          python-version: '3.10'
+          python-version: "3.10"
       - name: Install dependencies
-        # scipy and cython are required to build sdist
         run: |
+          # TEMP FIX: Retry apt update in case of mirror sync error
+          sudo sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirror.math.princeton.edu/pub/ubuntu/|g' /etc/apt/sources.list
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt clean
+          tries=5
+          until sudo apt update; do
+            ((tries--))
+            if [ $tries -le 0 ]; then
+              echo "APT update failed after multiple attempts."
+              exit 1
+            fi
+            echo "Retrying in 10 seconds..."
+            sleep 10
+          done
+
+          # Now install Python packages
           python -m pip install --upgrade pip
           pip install check-sdist
+
       - run: |
           check-sdist --inject-junk
 
