break scikit-learn build test

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -175,7 +175,9 @@ jobs:
           activate-environment: ""
 
       - name: Build scikit-learn
-        run: bash -l build_tools/azure/install.sh
+        run: |
+          bash -l build_tools/azure/install.sh
+          exit 143
 
       - name: Set random seed for nightly/manual runs
         if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
@@ -226,6 +228,7 @@ jobs:
           echo "job_id:" $job_id
 
       - name: Update tracking issue
+      # Note: skipped when 'build scikit-learn' failed
         if: ${{ always() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')}}
         run: |
           set -ex
